export const INVENTORY_LOADING = 'INVENTORY_LOADING';
export const INVENTORY_FAILED = 'INVENTORY_FAILED';
export const ADD_INVENTORY = 'ADD_INVENTORY';

export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const UPDATE_ITEM = 'UPDATE_ITEM';
