export const CUSTOMERS_LOADING = 'CUSTOMERS_LOADING';
export const CUSTOMERS_FAILED = 'CUSTOMERS_FAILED';
export const ADD_CUSTOMERS = 'ADD_CUSTOMERS';

export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
